# Sensitive
configuration:
    admin:
        username: auth
        password: you'd better change this
    database_uri: sqlite:///opp.sqlite
    directories:
        templates: templates
        media: media
    timezone: US/Eastern

# Public
podcast:
    title: One Page Podcast
    subtitle: An excellent new Podcast!
    description: This is a new Podcast. It hasn't even settled on a description!
    image: opp.jpg
    link: http://www.example.com
    author: Yours Truly
    email: contact@example.com
    language: en-us
    explicit: no
    keywords:
        - podcast
    category: Education
