# Sensitive
configuration:
    admin:
        username: Not yet used
        password: Not yet used
    database_uri: sqlite:///opp.sqlite
    directories:
        media: media
        static: static
        template: templates
    timezone: US/Eastern

# Public
podcast:
    title: One Page Podcast
    subtitle: A podcast on a single page
    description: |-
        You want to host your own podcast.  You don't need *anything* else.

        Boom.
    image: rss.png
    link: http://example.com
    author: Yours Truly
    email: yt@example.com
    language: en-us
    explicit: no
    keywords:
        - podcast
    category: Education
